FROM ubuntu:14.04

USER root

RUN apt-get -y update && apt-get install -y curl && apt-get install -y wget


# NGINX INSTALL
RUN apt-get install -y nginx
RUN echo 'service nginx restart' >> /etc/bash.bashrc
EXPOSE 80

# GIT INSTALL
RUN apt-get install -y  git

# NVM & NODE INSTALL
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 6.3.0

# NVM && NODE INSTALL
RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.30.1/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default
ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/v$NODE_VERSION/bin:$PATH
RUN echo 'nodejs --version' >> /etc/bash.bashrc

# PhantomJS Install
ADD phantomjs_install.sh /phantomjs_install.sh
RUN chmod u=rwx /*.sh
RUN /phantomjs_install.sh

# EXTRA PACKAGES
RUN apt-get install -y nano && apt-get install -y vim
RUN apt-get install -y lsof
